cc_binary(
    name = 'test_one',
    srcs=[
        "test_one.cc"
    ],
    linkopts = ["-lpthread"]
)


cc_binary(
    name = 'test_two',
    srcs=[
        "test_two.cc"
    ],
    linkopts = ["-lpthread"]
)


cc_binary(
    name = 'test_three',
    srcs=[
        "test_three.cc"
    ],
    linkopts = ["-lpthread"]
)
